services:
  # MCP Server in stdio mode (default)
  companies-house-mcp:
    build: .
    container_name: companies-house-mcp
    environment:
      - COMPANIES_HOUSE_API_KEY=${COMPANIES_HOUSE_API_KEY}
      - COMPANIES_HOUSE_BASE_URL=https://api.company-information.service.gov.uk
      - NODE_ENV=production
      - MCP_MODE=stdio
    volumes:
      # Mount logs directory if needed
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    # For MCP stdio communication
    networks:
      - mcp-network

  # MCP Server in HTTP mode
  companies-house-mcp-http:
    build: .
    container_name: companies-house-mcp-http
    environment:
      - COMPANIES_HOUSE_API_KEY=${COMPANIES_HOUSE_API_KEY}
      - COMPANIES_HOUSE_BASE_URL=https://api.company-information.service.gov.uk
      - NODE_ENV=production
      - MCP_MODE=http
      - PORT=${MCP_HTTP_PORT:-3000}
    ports:
      - "${MCP_HTTP_PORT:-3000}:${MCP_HTTP_PORT:-3000}"
    volumes:
      # Mount logs directory if needed
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mcp-network
    profiles:
      - http

networks:
  mcp-network:
    driver: bridge